name: Test

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
jobs:
  test:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: "Windows MSVC Release"
            os: windows-latest
            preset: windows-msvc-release
            compiler: msvc

          - name: "Linux GCC Release"
            os: ubuntu-latest
            preset: linux-gcc-release
            compiler: gcc-14

    steps:
      - uses: actions/checkout@v5

      - name: Setup Build Environment
        uses: ./.github/actions/setup-build-env
        with:
          preset: ${{ matrix.config.preset }}

      - name: Setup Cache
        uses: ./.github/actions/setup-cache
        with:
          preset: ${{ matrix.config.preset }}

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1.7.1
        with:
          compiler: ${{ matrix.config.compiler }}
          vcvarsall: ${{ contains(matrix.config.os, 'windows' )}}
          cmake: true
          ninja: true
          ccache: true

      - name: Configure
        run: cmake --preset ${{ matrix.config.preset }}

      - name: Build
        run: cmake --build --preset ${{ matrix.config.preset }}

      - name: Test
        run: ctest --output-on-failure --preset ${{ matrix.config.preset }}
